### ISSUE TITLE
Missing kernel sources for remix mini

### ISSUE THREAD

**Issue by heri16** [JideTechnology/remixos-kernel#2]
I would like to add touchscreen support to my Remix Mini device, but cannot do it due to missing kernel source. See my related pull request here: https://github.com/UDOOboard/linux_kernel/pull/18

Is there a support engineer from Jide that could work on this? http://www.chalk-elec.com/?p=2028

Note: nothing to do with RemixOS x86

**Comment by jide-opensource** [comment]
see https://github.com/JideTechnology/remixos-kernel/tree/jide_rm1/kernel
